spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres_product_data
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
server:
  port: 8081